# configure database PostgreSQL in test profile.

# Dados de conexão com o banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/springSearch
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Permite a execução do data.sql
spring.sql.init.mode=always

# Executa os scripts SQL somente após o Hibernate ter criado/atualizado o schema
spring.jpa.defer-datasource-initialization=true
